include:
  - project: 'Cacophony/gitlab-ci'
    ref: master
    file: '/go-service.yml'

variables:
  DEPLOYMENT_NAME: "processor"

stages:
  - prepare
  - release
  - staging

Go Lint:
  extends: .Go Service - Go Lint

Docker Build:
  extends: .Go Service - Docker Build

Docker Release:
  extends: .Go Service - Docker Release

Deploy Staging:
  extends: .Go Service - Deploy Staging

# TODO: put into gitlab.com/Cacophony/gitlab-ci

Sentry Release:
  stage: release
  image:
    name: getsentry/sentry-cli:latest
    entrypoint: [""]
  cache: {}
  only:
    refs:
      - master
  script:
    - sentry-cli releases new "${CI_COMMIT_SHA}"
    - sentry-cli releases set-commits --auto "${CI_COMMIT_SHA}"

Sentry Deploy Staging:
  variables:
    SENTRY_ENV: "staging"
  stage: staging
  image:
    name: getsentry/sentry-cli:latest
    entrypoint: [""]
  cache: {}
  only:
    refs:
      - master
  script:
    - sentry-cli releases deploys "${CI_COMMIT_SHA}" new -e ${SENTRY_ENV}
