run:
  timeout: 30m
  deadline: 30m # for old version of golangci-lint

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - golint
    - unconvert
    - goimports
    - maligned
    - unparam
    - prealloc
    - scopelint
