apiVersion: v1
kind: Secret
metadata:
  name: processor-secret
  namespace: cacophony
type: Opaque
stringData:
  discordTokens: "{{DISCORD_TOKENS}}"
  amqpDSN: "{{AMQP_DSN}}"
  loggingDiscordWebhook: "{{LOGGING_DISCORD_WEBHOOK}}"
  dbDSN: "{{DB_DSN}}"
  lastfmKey: "{{LASTFM_KEY}}"
  lastfmSecret: "{{LASTFM_SECRET}}"
  redisPassword: "{{REDIS_PASSWORD}}"
  featureflagUnleashURL: "{{FEATUREFLAG_UNLEASH_URL}}"
  featureflagUnleashInstanceID: "{{FEATUREFLAG_UNLEASH_INSTANCE_ID}}"
  errortrackingRavenDSN: "{{ERRORTRACKING_RAVEN_DSN}}"
  polrBaseURL: "{{POLR_BASE_URL}}"
  polrAPIKey: "{{POLR_API_KEY}}"
  iexCloudAPISecret: "{{IEXCLOUD_API_SECRET}}"
  discordAPIBase: "{{DISCORD_API_BASE}}"
  gcloudBucketName: "{{GCLOUD_BUCKET_NAME}}"
  objectStorageFQDN: "{{OBJECT_STORAGE_FQDN}}"
  weverseToken: "{{WEVERSE_TOKEN}}"
  instagramSessionIDs: "{{INSTAGRAM_SESSION_IDS}}"

---
apiVersion: v1
kind: Secret
metadata:
  name: processor-secret-files
  namespace: cacophony
type: Opaque
data:
  googleCloudCredentials: "{{GOOGLE_APPLICATION_CREDENTIALS}}"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      namespace: cacophony
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: "registry.gitlab.com/cacophony/processor:{{DOCKER_IMAGE_HASH}}"
          readinessProbe:
            httpGet:
              path: /status
              port: {{PORT}}
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: {{PORT}}
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
          - mountPath: "/secrets"
            name: google-cloud
            readOnly: true
          env:
          - name: PORT
            value: "{{PORT}}"
          - name: ENVIRONMENT
            value: "{{ENVIRONMENT}}"
          - name: CONCURRENT_PROCESSING_LIMIT
            value: "{{CONCURRENT_PROCESSING_LIMIT}}"
          - name: REDIS_ADDRESS
            value: "{{REDIS_ADDRESS}}"
          - name: CLUSTER_ENVIRONMENT
            value: "{{CLUSTER_ENVIRONMENT}}"
          - name: HASH
            value: "{{HASH}}"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/secrets/google-cloud"
          - name: DISCORD_TOKENS
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: discordTokens
          - name: AMQP_DSN
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: amqpDSN
          - name: DB_DSN
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: dbDSN
          - name: LOGGING_DISCORD_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: loggingDiscordWebhook
          - name: LASTFM_KEY
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: lastfmKey
          - name: LASTFM_SECRET
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: lastfmSecret
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: redisPassword
          - name: FEATUREFLAG_UNLEASH_URL
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: featureflagUnleashURL
          - name: FEATUREFLAG_UNLEASH_INSTANCE_ID
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: featureflagUnleashInstanceID
          - name: ERRORTRACKING_RAVEN_DSN
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: errortrackingRavenDSN
          - name: POLR_BASE_URL
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: polrBaseURL
          - name: POLR_API_KEY
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: polrAPIKey
          - name: IEXCLOUD_API_SECRET
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: iexCloudAPISecret
          - name: DISCORD_API_BASE
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: discordAPIBase
          - name: GCLOUD_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: gcloudBucketName
          - name: OBJECT_STORAGE_FQDN
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: objectStorageFQDN
          - name: WEVERSE_TOKEN
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: weverseToken
          - name: INSTAGRAM_SESSION_IDS
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: instagramSessionIDs
      volumes:
        - name: google-cloud
          secret:
            secretName: processor-secret-files
            items:
            - key: googleCloudCredentials
              path: google-cloud


---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: processor-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: processor