apiVersion: v1
kind: Secret
metadata:
  name: processor-secret
  namespace: cacophony
type: Opaque
stringData:
  discordTokens: "{{DISCORD_TOKENS}}"
  amqpDSN: "{{AMQP_DSN}}"
  loggingDiscordWebhook: "{{LOGGING_DISCORD_WEBHOOK}}"
  dbDSN: "{{DB_DSN}}"
  lastfmKey: "{{LASTFM_KEY}}"
  lastfmSecret: "{{LASTFM_SECRET}}"
  redisPassword: "{{REDIS_PASSWORD}}"
  featureflagUnleashURL: "{{FEATUREFLAG_UNLEASH_URL}}"
  featureflagUnleashInstanceID: "{{FEATUREFLAG_UNLEASH_INSTANCE_ID}}"
  errortrackingRavenDSN: "{{ERRORTRACKING_RAVEN_DSN}}"
  polrBaseURL: "{{POLR_BASE_URL}}"
  polrAPIKey: "{{POLR_API_KEY}}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      namespace: cacophony
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: "registry.gitlab.com/cacophony/processor:{{DOCKER_IMAGE_HASH}}"
          readinessProbe:
            httpGet:
              path: /status
              port: {{PORT}}
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: {{PORT}}
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
          - name: PORT
            value: "{{PORT}}"
          - name: ENVIRONMENT
            value: "{{ENVIRONMENT}}"
          - name: CONCURRENT_PROCESSING_LIMIT
            value: "{{CONCURRENT_PROCESSING_LIMIT}}"
          - name: REDIS_ADDRESS
            value: "{{REDIS_ADDRESS}}"
          - name: CLUSTER_ENVIRONMENT
            value: "{{CLUSTER_ENVIRONMENT}}"
          - name: HASH
            value: "{{HASH}}"
          - name: DISCORD_TOKENS
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: discordTokens
          - name: AMQP_DSN
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: amqpDSN
          - name: DB_DSN
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: dbDSN
          - name: LOGGING_DISCORD_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: loggingDiscordWebhook
          - name: LASTFM_KEY
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: lastfmKey
          - name: LASTFM_SECRET
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: lastfmSecret
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: redisPassword
          - name: FEATUREFLAG_UNLEASH_URL
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: featureflagUnleashURL
          - name: FEATUREFLAG_UNLEASH_INSTANCE_ID
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: featureflagUnleashInstanceID
          - name: ERRORTRACKING_RAVEN_DSN
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: errortrackingRavenDSN
          - name: POLR_BASE_URL
            valueFrom:
              secretKeyRef:
                name: worker-secret
                key: polrBaseURL
          - name: POLR_API_KEY
            valueFrom:
              secretKeyRef:
                name: worker-secret
                key: polrAPIKey


---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: processor-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: processor