apiVersion: v1
kind: Secret
metadata:
  name: processor-secret
  namespace: cacophony
type: Opaque
stringData:
  discordToken545676292154982400: "{{DISCORD_TOKEN_545676292154982400}}"
  amqpDSN: "{{AMQP_DSN}}"
  loggingDiscordWebhook: "{{LOGGING_DISCORD_WEBHOOK}}"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      namespace: cacophony
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: "registry.gitlab.com/cacophony/processor:{{DOCKER_IMAGE_HASH}}"
          readinessProbe:
            httpGet:
              path: /status
              port: {{PORT}}
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: {{PORT}}
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
          - name: PORT
            value: "{{PORT}}"
          - name: ENVIRONMENT
            value: "{{ENVIRONMENT}}"
          - name: CONCURRENT_PROCESSING_LIMIT
            value: "{{CONCURRENT_PROCESSING_LIMIT}}"
          - name: DISCORD_TOKEN_545676292154982400
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: discordToken545676292154982400
          - name: AMQP_DSN
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: amqpDSN
          - name: LOGGING_DISCORD_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: processor-secret
                key: loggingDiscordWebhook


---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: processor-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: processor